name = "ImageIO"
uuid = "82e4d734-157c-48bb-816b-45c225c6df19"
authors = ["Ian Butterworth"]
version = "0.5.5"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Netpbm = "f09324ee-3d7c-5217-9330-fc30815ba969"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
TiffImages = "731e570b-9d59-4bfa-96dc-6df516fadf69"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
FileIO = "1.2"
ImageCore = "0.8.1, 0.9"
Netpbm = "1.0"
PNGFiles = "0.3"
TiffImages = "0.3, 0.4"
julia = "1.3"

[extras]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ImageCore"]
