name = "ImageIO"
uuid = "82e4d734-157c-48bb-816b-45c225c6df19"
authors = ["Ian Butterworth"]
version = "0.1.1"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"

[compat]
FileIO = "1.2"
PNGFiles = "0.1.2"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
